# Generated by Django 5.0.6 on 2024-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Subscriber', 'Subscriber'), ('Moderator', 'Moderator')], default='Patient', max_length=200),
        ),
    ]
