# Generated by Django 5.0.6 on 2024-08-05 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_your_suggestion_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors_panel_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_doctor', models.CharField(max_length=200)),
                ('graduation_course', models.TextField(max_length=300)),
                ('post_graduation_course', models.TextField(max_length=300)),
                ('diploma', models.CharField(max_length=300)),
                ('specialization', models.CharField(max_length=300)),
                ('Accademic_details', models.TextField(max_length=300)),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('teshil', models.CharField(max_length=120)),
                ('block', models.CharField(max_length=120)),
                ('thana', models.CharField(max_length=120)),
                ('tehsil', models.CharField(max_length=120)),
                ('clinic_address', models.TextField()),
                ('document', models.URLField(blank=True, default=None, null=True)),
                ('picture', models.URLField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Approved', 'Aproved')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
