# Generated by Django 5.0.6 on 2024-08-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_doctors_panel_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors_panel_form',
            name='teshil',
        ),
    ]
