# Generated by Django 5.0.6 on 2024-08-19 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_your_problem_form_your_problem_teshil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_panel_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_hospital', models.CharField(max_length=200)),
                ('hospital_address', models.TextField()),
                ('name_of_manager', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=120)),
                ('thana', models.CharField(max_length=120)),
                ('tehsil', models.CharField(max_length=120)),
                ('free_facility', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.URLField(blank=True, default=None, null=True)),
                ('picture', models.URLField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Approved', 'Aproved')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
