# Generated by Django 5.0.6 on 2024-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_hospital_panel_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_panel_form',
            name='hospital_address',
            field=models.TextField(max_length=800),
        ),
    ]
