# Generated by Django 5.0.6 on 2024-07-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
