# Generated by Django 5.0.6 on 2024-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_announcement_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Url', models.URLField()),
            ],
        ),
    ]
