# Generated by Django 5.0.6 on 2024-07-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_navigation_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navigation_links',
            new_name='Navigation_link',
        ),
    ]
