# Generated by Django 5.0.6 on 2024-07-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Team_member',
        ),
    ]
