# Generated by Django 5.0.6 on 2024-07-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_team_team_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_member',
            old_name='Organiztion',
            new_name='Organization',
        ),
    ]
