# Generated by Django 5.0.6 on 2024-07-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_socialmedia_and_helpline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia_and_helpline',
            options={'verbose_name': 'Social Media Links', 'verbose_name_plural': 'Social Media Links and HelpLine Number'},
        ),
    ]
