# Generated by Django 5.0.6 on 2024-08-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_footer_and_home_page_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='team_member',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='team_member',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
