# Generated by Django 5.0.6 on 2024-08-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_team_member_instagram_team_member_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
