# Generated by Django 5.0.6 on 2024-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_team_member_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation_link2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Url', models.URLField()),
            ],
        ),
    ]
