# Generated by Django 5.0.6 on 2024-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_navigation_link2'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_and_home_page_data',
            name='become_a_partner_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer_and_home_page_data',
            name='donate_to_support_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
