# Generated by Django 5.0.6 on 2024-09-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_footer_and_home_page_data_about_us_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='announcement',
            new_name='health_tips',
        ),
        migrations.DeleteModel(
            name='footer_and_home_page_data',
        ),
        migrations.DeleteModel(
            name='SocialMedia_and_HelpLine',
        ),
        migrations.DeleteModel(
            name='Team_member',
        ),
    ]
