# Generated by Django 5.0.6 on 2024-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_rename_announcement_health_tips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=500)),
            ],
        ),
    ]
