# Generated by Django 5.0.6 on 2024-09-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_health_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(default='https://drive.google.com/thumbnail?id=1tnvzDrM46Rdih8Kvg_wFYYpm1ht-0yyp&sz=s4000')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('experience', models.IntegerField()),
                ('work', models.CharField(max_length=300)),
                ('specialization', models.ManyToManyField(related_name='doctors', to='Home.specialization')),
            ],
        ),
    ]
