# Generated by Django 5.0.6 on 2024-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_ask_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_doctor',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
