from website.admin import admin_site
from .models import *

admin_site.register(Your_problem_form)
admin_site.register(Your_suggestion_form)
admin_site.register(doctors_panel_form)
admin_site.register(hospital_panel_form)
admin_site.register(judicial_help_panel_form)
admin_site.register(Plantation_form)
admin_site.register(Save_water_form)
admin_site.register(arogya_form)
admin_site.register(Clean_India_form)
admin_site.register(Rakt_veer_form)
admin_site.register(judicial_help_form)
admin_site.register(kanya_daan_form)
admin_site.register(shiksha_sankalp_form)
admin_site.register(Employment_generation_form)
admin_site.register(Road_safety_awareness_form)
admin_site.register(Cancer_awareness_form)
admin_site.register(Volunteer_form)